### ISSUE TITLE
I have compiled  this project complete.

### ISSUE THREAD

**Issue by BIIYANG** [mdexSwap/contracts#6]
1.the configuration of truffle-config.js 
compilers: {
    solc: {
         version: "^0.6.0",    // Fetch exact version from solc-bin (default: truffle's version)
    }
  }

2. Factory.sol  
   modifiy the code from chainId := chainid to chainId := chainid()

   modify every functions and variables of MdexERC20 -- just to add "override" flag to them.

   modify MdexPair, just to implements the interface IMdexPair,  NO MdexERC20 !  And then, copy all the  MdexERC20 code  to the MdexPair.    That's all !  The others erros, please reference the building console logs.

  Good Luck !

**Comment by myx75** [comment]
thinks

**Comment by dh12306** [comment]
> 1. MdexERC20

could u share ur code on github？ thx very much

**Comment by myx75** [comment]
@dh12306 
参考这里：https://github.com/Wapdex/wapdex
